genai:
  webAgents:
    - name: Chat GPT
      url: https://chatgpt.com
    - name: Deep AI
      url: https://deepai.org/chat/free-chatgpt
    - name: Stable fusion
      url: https://deepai.org/chat/free-chatgpt
    # - name: Deepseek
    #   url: https://deepai.org/chat/free-chatgpt
app:
  title: Util4Ops component
update:
  version: '2'
